### ISSUE TITLE
Is it possible to handle gestures on blocks and trigger some action based on those gestures? 

### ISSUE THREAD

**Issue by thembangpa** [CoderNamedHendrick/schematics#2]
Thank you for publishing the library 👍🏻. 
I have been playing around with the example app and was wondering if it's possible to handle gestures on blocks and trigger some action based on those gestures?  For example: show some context menu or pop ups for block specific details?

**Comment by CoderNamedHendrick** [comment]
Hey, @thembangpa. Thank you for checking out the package. I believe a listener can be exposed to communicate block taps. Showing any action on tap would be left to the developer. I'll create an issue and add that to a later update.

**Comment by CoderNamedHendrick** [comment]
#3  resolves this issue. Closing issue now

**Comment by CoderNamedHendrick** [comment]
I thought about it some more, asides communicating the global position, I think we should be communicating the local position

**Comment by CoderNamedHendrick** [comment]
Resolved with #4

**Comment by CoderNamedHendrick** [comment]
A new version is up @thembangpa, thank you for the feedback
